version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.3
  rebase-strategy: disabled
